### ISSUE TITLE
Can you explain how the segmentation is added to the image?

### ISSUE THREAD

**Issue by V4A001** [ibaiGorordo/ONNX-TopFormer-Semantic-Segmentation#1]
Your code is amazingly simple and good readable.  Thank you.

I am trying to see how to get my model working in ONNX (https://github.com/WongKinYiu/yolov7/issues/797#issuecomment-1354584917). I am working on Yolo segmentation and running through a bunch of examples. 

Your output is float32[1,150,64,64], how is that converted to the masks you put on the image?

`
def process_output(self, outputs): 

		return np.squeeze(np.argmax(outputs[0], axis=1))

	def draw_segmentation(self, image, alpha = 0.5):

		return util_draw_seg(self.seg_map, image, alpha)
`

![image](https://user-images.githubusercontent.com/9630343/208325047-2d0852cf-4bd9-49bc-a4ac-bc9731f05e05.png)

**Comment by ibaiGorordo** [comment]
The Yolo model is Instance Segmentation, while this one is semantic segmentation. Instance segmentation is much harder to process the output of semantic segmentation. 

Maybe start with Yolov5, which seems to be a bit easier to process: https://github.com/ultralytics/yolov5#segmentation--new

**Comment by ibaiGorordo** [comment]
Here is the example for Yolov5: https://github.com/ibaiGorordo/ONNX-YOLOv5-Instance-Segmentation

**Comment by V4A001** [comment]
I tried to replicate situation with Yolov5 library. The idea is that the output of the tensor gives multiple masks and with NMP the best masks are selected, and then added to the image. That is one of the ideas in YoloV7,
https://github.com/ultralytics/yolov5/issues/10578

**Comment by ibaiGorordo** [comment]
Yeah, using a Yolov7 model in Yolov5 is not going to work in many cases because the output is different, so that issue in the Yolov5 repo should probably be closed. What I meant to say is that you can train a YOLOv5 model and use the code I shared for inference. If you want to use the YOLOv7 instance segmentation, you will have to write the logic to process the output.

**Comment by ibaiGorordo** [comment]
Also closing this issue since it is not related to the TopFormer model.
